Add files via upload
divyam3897/vimrc pull request #2
Opened 2017-09-30 19:27 UTC by tanmaysachan

Single script to apply the new vimrc

2017-09-30 19:30 UTC, divyam3897 reviewed
Update the README with the run instructions using the script and write a good commit message

2017-09-30 19:37 UTC, divyam3897 commented on script.py
> +
Remove all these empty lines.

2017-09-30 19:37 UTC, divyam3897 commented on README.md
> +
Remove the empty lines

2017-09-30 19:38 UTC, divyam3897 requested changes
Squash all the commits into one and remove the irrelevant changes

2017-10-01 12:36 UTC, divyam3897 requested changes

2017-10-01 12:36 UTC, divyam3897 commented on script.py
> +
Remove these empty lines please!!

2017-10-01 13:42 UTC, tanmaysachan commented
That should be it?

2017-10-02 06:40 UTC, divyam3897 requested changes
Write a good commit message please. Follow https://chris.beams.io/posts/git-commit/

2017-10-03 13:58 UTC, merged

2017-10-03 13:59 UTC, divyam3897 commented
It has been merged thanks